export interface SpacingScale {
	/**
	 * With + or * depending on whether scale is generated by increment or multiplier.
	 */
	operator?: '+' | '*';
	/**
	 * The amount to increment each step by.
	 */
	increment?: number;
	/**
	 * Number of steps to generate in scale.
	 */
	steps?: number;
	/**
	 * The value to medium setting in the scale.
	 */
	mediumStep?: number;
	/**
	 * Unit that the scale uses, eg. rem, em, px.
	 */
	unit?: 'px' | 'em' | 'rem' | 'vh' | 'vw' | '%';
}

export interface SpacingSizes {
	/**
	 * Name of the space size preset, translatable.
	 */
	name?: string;
	/**
	 * Unique identifier for the space size preset. For best cross theme compatibility these should be in the form '10','20','30','40','50','60', etc. with '50' representing the 'Medium' size step.
	 */
	slug?: string;
	/**
	 * CSS space-size value, including units.
	 */
	size?: string;
}
