import { ExtensionContext, StatusBarAlignment, commands, languages, window, workspace } from 'vscode';

import { CssVariableCompletionItemProvider } from './css-variable-completion-item-provider';
import { CssVariableHoverProvider } from './css-variable-hover-provider';
import refreshProviders from './refresh-providers';
import { getThemeJsonPath, setThemeJsonPath } from './theme-json';

export async function activate( context: ExtensionContext ) {
	const statusBarItem = window.createStatusBarItem( StatusBarAlignment.Left, -100 );
	statusBarItem.tooltip = 'Using autocompletion data generated by the theme.json';

	const documentSelectors = [
		'css',
		'html',
		'javascript',
		'javascriptreact',
		'json',
		'jsonc',
		'less',
		'markdown',
		'php',
		'plaintext',
		'scss',
		'sass',
		'typescript',
		'typescriptreact',
		'vue',
		'vue-html',
	];

	// Providers.
	const cssVariableCompletionProvider = new CssVariableCompletionItemProvider();
	const cssVariableHoverProvider = new CssVariableHoverProvider();

	const doRefreshProviders = () => {
		let timeout = null;

		if ( timeout ) {
			clearTimeout( timeout );
		}

		statusBarItem.text = '$(sync~spin) theme.json';
		statusBarItem.show();

		refreshProviders( {
			cssVariableCompletionProvider,
			cssVariableHoverProvider,
		} );

		// If the refreshing process occurs too quickly, this timeout will result
		// in the spinning sync icon being displayed for nearly a second.
		timeout = setTimeout( () => {
			statusBarItem.text = '$(json) theme.json';
		}, 800 );
	};

	// Commands.
	const setThemeJsonPathCommand = commands.registerCommand( 'wpBlockThemeCompanion.setThemeJsonPath', () =>
		setThemeJsonPath( doRefreshProviders )
	);

	// Subscribe to the context.
	context.subscriptions.push(
		setThemeJsonPathCommand,
		languages.registerCompletionItemProvider( documentSelectors, cssVariableCompletionProvider ),
		languages.registerHoverProvider( documentSelectors, cssVariableHoverProvider ),
		// Referesh providers everytime we save the theme.json.
		workspace.onDidSaveTextDocument( ( document ) => {
			const projectRoot = workspace.workspaceFolders?.[ 0 ].uri.path ?? '';
			const filePath = document.uri.path ?? '';
			const relativePath = filePath?.replace( `${ projectRoot }/`, '' );

			if ( relativePath !== getThemeJsonPath() ) {
				return;
			}

			doRefreshProviders();
		} )
	);

	// Get the theme.json path from config.
	const themeJsonPath = getThemeJsonPath();

	// If no theme.json is provided or the json does not have settings then do not proceed.
	if ( ! themeJsonPath ) {
		return;
	}

	// It executes on activation when the theme.json path is already set.
	doRefreshProviders();
}

export function deactivate() {}
